### ISSUE TITLE
Create an AegisID custom resource

### ISSUE THREAD

**Issue by v0lkan** [zerotohero-dev/aegis#188]
`ClusterSPIFFEID` that Aegis uses to identify the workloads contains domain-specific information and can be error-prone to manage. Here’s an example ClusterSPIFFEID

```yaml
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: aegis-workload-demo
spec:
  # SPIFFE ID `MUST` start with "spiffe://aegis.z2h.dev/workload/$workloadName/ns/"
  # for `aegis-safe` to recognize the workload and dispatch secrets to it.
  spiffeIDTemplate: "spiffe://aegis.z2h.dev\
    /workload/aegis-workload-demo\
    /ns/{{ .PodMeta.Namespace }}\
    /sa/{{ .PodSpec.ServiceAccountName }}\
    /n/{{ .PodMeta.Name }}"
  podSelector:
    matchLabels:
      app.kubernetes.io/name: aegis-workload-demo
  workloadSelectorTemplates:
  - "k8s:ns:{{ .PodMeta.Namespace }}"
  - "k8s:sa:{{ .PodSpec.ServiceAccountName }}"

```

Instead of that using something like this will be more concise, and less error prone.
It can generate the ClusterSPIFFEID behind-the-scenes:

```yaml
apiVersion: aegis.z2h.dev/v1alpha1
kind: AegisID
metadata:
  name: aegis-workload-demo
spec:
  workloadName: aegis-workload-demo
  workloadNamespace: <optional | default>
  workloadServiceAccoount: <optional | default >
  workloadTrustDomain: <optional | aegis.z2h.dev >

```

^ This will leak much less domain-specific information; much easier to manage; and less error-prone.

**Comment by v0lkan** [comment]
Dumping my chatter with GPT.


I have this custom resource:


```yaml
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: aegis-workload-demo
spec:
  # SPIFFE ID `MUST` start with "spiffe://aegis.z2h.dev/workload/$workloadName/ns/"
  # for `aegis-safe` to recognize the workload and dispatch secrets to it.
  spiffeIDTemplate: "spiffe://aegis.ist\
    /workload/aegis-workload-demo\
    /ns/{{ .PodMeta.Namespace }}\
    /sa/{{ .PodSpec.ServiceAccountName }}\
    /n/{{ .PodMeta.Name }}"
  podSelector:
    matchLabels:
      app.kubernetes.io/name: aegis-workload-demo
  workloadSelectorTemplates:
  - "k8s:ns:{{ .PodMeta.Namespace }}"
  - "k8s:sa:{{ .PodSpec.ServiceAccountName }}"
```

I want to abstract domain-specific information, and manage it with a simpler customer resource like this:

```yaml
apiVersion: aegis.z2h.dev/v1alpha1
kind: AegisID
metadata:
  name: aegis-workload-demo
spec:
  workloadName: aegis-workload-demo
  workloadNamespace: <optional | default>
  workloadServiceAccoount: <optional | default >
  workloadTrustDomain: <optional | aegis.ist >
```

How shall I proceed?


----


To achieve this abstraction, you will need to create a custom Kubernetes Operator to manage your new AegisID custom resource. The Operator will watch for changes in the AegisID resource and update the ClusterSPIFFEID resource accordingly.

Define your AegisID Custom Resource Definition (CRD):
Create a file called aegisid_crd.yaml with the following content:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aegisids.aegis.z2h.dev
spec:
  group: aegis.z2h.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                workloadName:
                  type: string
                workloadNamespace:
                  type: string
                  nullable: true
                workloadServiceAccount:
                  type: string
                  nullable: true
                workloadTrustDomain:
                  type: string
                  nullable: true
  scope: Namespaced
  names:
    plural: aegisids
    singular: aegisid
    kind: AegisID
    shortNames:
      - aid
```

Apply the CRD to your cluster:

```bash
kubectl apply -f aegisid_crd.yaml
```

Create a Kubernetes Operator:

You can use the Kubebuilder or Operator SDK to create your custom operator. Here, we'll use the Operator SDK.

First, install the Operator SDK CLI. Follow the official installation guide for your platform.

Next, create a new Operator project:

```bash
operator-sdk init --domain aegis.z2h.dev --repo github.com/yourusername/aegis-operator
cd aegis-operator
```

Create a new API and controller for the AegisID resource:

```bash
operator-sdk create api --group aegis.z2h.dev --version v1alpha1 --kind AegisID --resource --controller
```

Update the generated aegisid_types.go file to match the desired AegisID spec.
Implement the reconciliation logic in the aegisid_controller.go file. In the Reconcile method, watch for changes in AegisID resources and create/update the corresponding ClusterSPIFFEID resource as needed. Use the Go Kubernetes client to interact with the Kubernetes API.

Build and deploy the Operator:

```bash
make docker-build docker-push IMG=<your-docker-image>
make deploy IMG=<your-docker-image>
```

After completing these steps, your Operator should be running in your cluster, managing the AegisID resources and their corresponding ClusterSPIFFEID resources as desired.


----

Can you write step 4 for me?

----

Certainly! In this example, I'll be using the controller-runtime library, which is included in Operator SDK projects by default. Here's a basic implementation for the Reconcile method in the aegisid_controller.go file:

```go
package controllers

import (
	"context"

	"github.com/go-logr/logr"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"

	aegisv1alpha1 "github.com/yourusername/aegis-operator/api/v1alpha1"
	spirev1alpha1 "github.com/spiffe/spire/api/spiffeid/v1alpha1"
)

type AegisIDReconciler struct {
	client.Client
	Log    logr.Logger
	Scheme *runtime.Scheme
}

func (r *AegisIDReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	log := r.Log.WithValues("aegisid", req.NamespacedName)

	// Fetch AegisID resource
	aegisID := &aegisv1alpha1.AegisID{}
	err := r.Get(ctx, req.NamespacedName, aegisID)
	if err != nil {
		if errors.IsNotFound(err) {
			log.Info("AegisID resource not found. Ignoring.")
			return ctrl.Result{}, nil
		}
		log.Error(err, "Failed to get AegisID")
		return ctrl.Result{}, err
	}

	// Set defaults for optional fields
	workloadNamespace := aegisID.Spec.WorkloadNamespace
	if workloadNamespace == "" {
		workloadNamespace = "default"
	}

	workloadServiceAccount := aegisID.Spec.WorkloadServiceAccount
	if workloadServiceAccount == "" {
		workloadServiceAccount = "default"
	}

	workloadTrustDomain := aegisID.Spec.WorkloadTrustDomain
	if workloadTrustDomain == "" {
		workloadTrustDomain = "aegis.ist"
	}

	// Construct desired ClusterSPIFFEID
	desiredClusterSPIFFEID := &spirev1alpha1.ClusterSPIFFEID{
		ObjectMeta: metav1.ObjectMeta{
			Name:      aegisID.Name,
			Namespace: req.Namespace,
		},
		Spec: spirev1alpha1.ClusterSPIFFEIDSpec{
			SpiffeIDTemplate: "spiffe://" + workloadTrustDomain +
				"/workload/" + aegisID.Spec.WorkloadName +
				"/ns/" + workloadNamespace +
				"/sa/" + workloadServiceAccount +
				"/n/{{ .PodMeta.Name }}",
			PodSelector: spirev1alpha1.PodSelector{
				MatchLabels: aegisID.Labels,
			},
			WorkloadSelectorTemplates: []string{
				"k8s:ns:" + workloadNamespace,
				"k8s:sa:" + workloadServiceAccount,
			},
		},
	}

	// Check if ClusterSPIFFEID exists
	foundClusterSPIFFEID := &spirev1alpha1.ClusterSPIFFEID{}
	err = r.Get(ctx, req.NamespacedName, foundClusterSPIFFEID)
	if err != nil && errors.IsNotFound(err) {
		log.Info("Creating a new ClusterSPIFFEID", "ClusterSPIFFEID.Namespace", desiredClusterSPIFFEID.Namespace, "ClusterSPIFFEID.Name", desiredClusterSPIFFEID.Name)
		err = r.Create(ctx, desiredClusterSPIFFEID)
		if err != nil {
			log.Error(err, "Failed to create new ClusterSPIFFEID", "ClusterSPIFFEID.Namespace", desired
```


----

you response cut out after `log.Error(err, "Failed to create new ClusterSPIFFEID",`.


----

Apologies for that. Here's the continuation of the Reconcile method:

```go
			log.Error(err, "Failed to create new ClusterSPIFFEID", "ClusterSPIFFEID.Namespace", desiredClusterSPIFFEID.Namespace, "ClusterSPIFFEID.Name", desiredClusterSPIFFEID.Name)
			return ctrl.Result{}, err
		}
		return ctrl.Result{Requeue: true}, nil
	} else if err != nil {
		log.Error(err, "Failed to get ClusterSPIFFEID")
		return ctrl.Result{}, err
	}

	// Update the ClusterSPIFFEID if it differs from the desired state
	if !reflect.DeepEqual(foundClusterSPIFFEID.Spec, desiredClusterSPIFFEID.Spec) {
		foundClusterSPIFFEID.Spec = desiredClusterSPIFFEID.Spec
		log.Info("Updating ClusterSPIFFEID", "ClusterSPIFFEID.Namespace", foundClusterSPIFFEID.Namespace, "ClusterSPIFFEID.Name", foundClusterSPIFFEID.Name)
		err = r.Update(ctx, foundClusterSPIFFEID)
		if err != nil {
			log.Error(err, "Failed to update ClusterSPIFFEID", "ClusterSPIFFEID.Namespace", foundClusterSPIFFEID.Namespace, "ClusterSPIFFEID.Name", foundClusterSPIFFEID.Name)
			return ctrl.Result{}, err
		}
		return ctrl.Result{Requeue: true}, nil
	}

	return ctrl.Result{}, nil
}

func (r *AegisIDReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&aegisv1alpha1.AegisID{}).
		Owns(&spirev1alpha1.ClusterSPIFFEID{}).
		Complete(r)
}
```


This implementation of the Reconcile method fetches the AegisID resource, constructs the desired ClusterSPIFFEID based on the AegisID, checks if the ClusterSPIFFEID exists, and creates or updates it if necessary. Note that this example assumes you have imported the spirev1alpha1 package for the ClusterSPIFFEID API. You may need to adjust the import path depending on your actual project setup.

----


So, I guess once the code is done, I containerize it and then install the the cluster as a… Deployment?


----

Yes, that's correct! Once you have completed writing your operator code, you'll need to containerize it and deploy it to your Kubernetes cluster as a Deployment.

Here are the steps to containerize and deploy the operator:

Build the operator Docker image:

The operator-sdk has already generated a Dockerfile for you in the project directory. You can build the image using docker or podman.

```bash
make docker-build docker-push IMG=<your-docker-image>
```

Replace <your-docker-image> with the desired image name, including the registry if you plan to push it to a remote registry.

Deploy the operator to your Kubernetes cluster:
Update the config/manager/manager.yaml file to use the image you built in the previous step. Change the image field under spec.template.spec.containers to match <your-docker-image>.

Next, apply the manifests to your cluster:

```bash
make deploy IMG=<your-docker-image>
```

This command will create a namespace, deploy the necessary RBAC resources, and create a Deployment for your operator. The operator will run with a single replica by default, but you can adjust the replica count in the config/manager/manager.yaml file if needed.

After running the make deploy command, you can check the status of your operator using kubectl:

```bash
kubectl get deployments -n <operator-namespace>
```

Replace <operator-namespace> with the namespace where your operator is deployed. By default, the Operator SDK creates a namespace with the format <your-project-name>-system, but you can customize it in the config/default/kustomization.yaml file.

You can also check the logs of your operator to ensure it's running as expected:

```bash
kubectl logs -n <operator-namespace> -l control-plane=controller-manager -c manager --tail=-1 -f
```

This command will stream the logs of the manager container in the operator Deployment, which is where your operator code runs.
