### ISSUE TITLE
Get rid of the admin token

### ISSUE THREAD

**Issue by v0lkan** [zerotohero-dev/aegis#26]
Here’s the reasoning:

We already secure `sentinel`-to-`safe` connectivity using mTLS. So, as long as no one can impersonate `sentinel`, `sentinel` can happily authenticate and authorize with safe.

We just need to secure access to sentinel with a role similar to this:

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: aegis-system
  name: aegis-admin
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
```

Then, only the users bound to this role (and also cluster admins) can `kubectl exec` on sentinel.

Since sentinel does not have any external-facing API, that will be the only way to generate secrets on the system.

Then, assuming SPIRE is happy as a clam, creating a secret will be as simple as something like this:

```bash
kubectl exec -it aegis-sentinel-aabbcc -- /bin/aegis secret \
--id workloadSvid \
--value "secretValue"
```
